packages:
  - apps/*
  - packages/*

catalog:
  "@wisemen/eslint-config-vue": "1.1.0"
  "eslint": "9.25.1"

  "typescript": "5.8.3"
  "vitest": "3.1.2"
  "zod": "3.24.3"

  "@payloadcms/db-postgres": "3.35.1"
  "@payloadcms/next": "3.35.1"
  "@payloadcms/plugin-seo": "3.35.1"
  "@payloadcms/richtext-lexical": "3.35.1"
  "@payloadcms/storage-s3": "3.35.1"
  "@payloadcms/ui": "3.35.1"
  "@payloadcms/live-preview-vue": "3.35.1"
  "@payloadcms/live-preview": "3.35.1"
  "payload": "3.35.1"
  "@payloadcms/plugin-multi-tenant": "3.35.1"

  "@orpc/server": "1.1.0"
  "@orpc/contract": "1.1.0"
  "@orpc/client": "1.1.0"
