packages:
  - apps/*
  - packages/*
catalogs:
  lint:
    '@wisemen/eslint-config-vue': 1.7.3
    eslint: 9.37.0
  types:
    typescript: 5.9.3
    zod: 4.1.11
  test:
    vitest: 3.2.4
  payload:
    '@payloadcms/db-postgres': 3.58.0
    '@payloadcms/next': 3.58.0
    '@payloadcms/plugin-seo': 3.58.0
    '@payloadcms/richtext-lexical': 3.58.0
    '@payloadcms/storage-s3': 3.58.0
    '@payloadcms/ui': 3.58.0
    '@payloadcms/live-preview-vue': 3.58.0
    '@payloadcms/live-preview': 3.58.0
    payload: 3.58.0
    '@payloadcms/plugin-multi-tenant': 3.58.0
  orpc:
    '@orpc/server': 1.9.3
    '@orpc/contract': 1.9.3
    '@orpc/client': 1.9.3
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
