packages:
  - apps/*
  - packages/*
catalogs:
  lint:
    '@wisemen/eslint-config-vue': 1.1.0
    eslint: 9.26.0
  types:
    typescript: 5.8.3
    zod: 3.24.4
  test:
    vitest: 3.1.3
  payload:
    '@payloadcms/db-postgres': 3.49.0
    '@payloadcms/next': 3.49.0
    '@payloadcms/plugin-seo': 3.49.0
    '@payloadcms/richtext-lexical': 3.49.0
    '@payloadcms/storage-s3': 3.49.0
    '@payloadcms/ui': 3.49.0
    '@payloadcms/live-preview-vue': 3.37.0
    '@payloadcms/live-preview': 3.49.0
    payload: 3.49.0
    '@payloadcms/plugin-multi-tenant': 3.49.0
  orpc:
    '@orpc/server': 1.2.0
    '@orpc/contract': 1.2.0
    '@orpc/client': 1.2.0
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
