packages:
  - apps/*
  - packages/*

catalog:
  "@wisemen/eslint-config-vue": "1.1.0"
  "eslint": "9.24.0"
  "typescript": "5.8.2"
  "vitest": "3.1.1"
  "zod": "3.24.2"
  "@payloadcms/db-postgres": "3.28.1"
  "@payloadcms/next": "3.28.1"
  "@payloadcms/plugin-seo": "3.28.1"
  "@payloadcms/richtext-lexical": "3.28.1"
  "@payloadcms/storage-s3": "3.28.1"
  "@payloadcms/ui": "3.28.1"
  "payload": "3.28.1"
  "@payloadcms/plugin-multi-tenant": "3.28.1"
  "@orpc/server": "1.0.0-beta.1"
  "@orpc/contract": "1.0.0-beta.1"
  "@orpc/client": "1.0.0-beta.1"
