import { z } from 'zod'

import { ERROR_NOT_FOUND } from '../../errors/errors'
import { publicProcedure } from '../../procedures/procedures'

const getPageBySlug = publicProcedure
  .input(z.object({
    slug: z.string(),
  }))
  // NOTE: This type gets generated by payload, so we put any and cast it later
  .output(z.any())
  .errors({
    ERROR_NOT_FOUND,
  })

export const PAGES_CONTRACT = {
  getPageBySlug,
}
